
[package]
name = "mr-connectome"
version = "4.5.0"
authors = ["Dr.G", "Timothy Busbice"]
description = "A rust simulation of a simplified c.ellegans connectome"
license = "MIT OR Apache-2.0"
#repository = "NA"
#exclude = ["*.png", "doc/reference", "doc/formats"]
publish = false

[dependencies]
csv = { version = "1.3"}

#[build-dependencies]
#cc = "1.0"


