[package]
name = "clib-test"
version = "0.1.0"
edition = "2021"


[features]
default = ["libxmp"]

[dependencies]
libxmp = {path = "./3rdparty/libxmp", optional = true}


[build-dependencies]
cc = "1.0"

