
[package]
name = "libxmp"
version = "4.5.0"
authors = ["Wrapped by Alula, Dr.G, et. al."]
description = "A rust wrapper for libxmp"
license = "MIT OR Apache-2.0"
#repository = "NA"
#exclude = ["*.png", "doc/reference", "doc/formats"]
publish = false


[build-dependencies]
cc = "1.0"


