# Core definitions
.core-defs:
  variables:
    CORENAME: doukutsu_rs

include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/rust-windows-x64.yml'
    
  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/rust-linux-x64.yml'

  # MacOS/iOS/tvOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/rust-apple.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/rust-android-jni.yml'
    
  #################################### MISC ##################################
  # Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static


##############################################################################
#################################### STAGES ##################################
##############################################################################
#

################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-rust-windows-x64-default
    - .core-defs
        
# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-rust-linux-x64-default
    - .core-defs

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .libretro-rust-osx-x86_64-default
    - .core-defs
# MacOS ARM 64-bit
libretro-build-osx-arm64:
  extends:
    - .libretro-rust-osx-arm64-default
    - .core-defs

################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .libretro-rust-android-jni-armeabi-v7a
    - .core-defs
# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-rust-android-jni-arm64-v8a
    - .core-defs
# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-rust-android-jni-x86_64
    - .core-defs
# Android 32-bit x86
android-x86:
  extends:
    - .libretro-rust-android-jni-x86
    - .core-defs

# iOS
libretro-build-ios-arm64:
  extends:
    - .libretro-rust-ios-arm64-default
    - .core-defs

# tvOS
libretro-build-tvos-arm64:
  extends:
    - .libretro-rust-tvos-arm64-default
    - .core-defs
